"""
Multifamily Property Backward Analysis Model
=============================================
Works BACKWARD from retirement income goal to determine exact deal criteria.
Validates: debt/LTV feasibility, investor marketability, creative financing options.

Author: Generated by Kiro
"""

import math
from dataclasses import dataclass, field
from typing import Optional


# =============================================================================
# SECTION 1: DATA CLASSES FOR INPUTS
# =============================================================================

@dataclass
class RetirementGoal:
    """User's retirement income and timeline targets."""
    annual_passive_income: float = 200_000  # Net after debt service, expenses, reserves
    timeline_years: int = 5
    min_cash_on_cash: float = 0.10  # 10%
    num_properties: int = 3
    tax_rate: float = 0.30  # Combined federal + state effective rate
    cash_available: float = 150_000


@dataclass
class DebtAssumptions:
    """Lending parameters for conventional financing."""
    ltv_min: float = 0.65
    ltv_target: float = 0.75
    ltv_max: float = 0.80
    dscr_required: float = 1.25
    interest_rate: float = 0.065  # 6.5%
    amortization_years: int = 30
    loan_term_years: int = 7
    origination_costs_pct: float = 0.025  # 2.5%


@dataclass
class MarketAssumptions:
    """Local market rent and expense assumptions."""
    avg_market_rent_per_unit: float = 1_200
    avg_unit_sf: float = 850
    vacancy_rate: float = 0.07  # 7%
    expense_ratio: float = 0.45  # 45% of EGI
    annual_rent_growth: float = 0.03  # 3%
    annual_expense_growth: float = 0.025  # 2.5%
    cap_rate_market: float = 0.065  # 6.5% market cap
    exit_cap_rate: float = 0.070  # 7.0% exit cap (conservative)
    price_per_unit_market: float = 95_000



@dataclass
class InvestorAssumptions:
    """Passive investor return thresholds for syndication marketability."""
    preferred_return: float = 0.08  # 8% annual pref
    target_equity_multiple: float = 2.0  # 2.0x over hold
    target_irr: float = 0.17  # 17% IRR
    hold_period_years: int = 5
    gp_promote_after_pref: float = 0.30  # 30% to GP after pref hurdle
    min_investment_per_lp: float = 50_000
    reserve_months: int = 6  # Operating reserve


@dataclass
class CreativeFinanceAssumptions:
    """Parameters for seller financing and creative structures."""
    seller_finance_rate: float = 0.05  # 5% seller carry rate
    seller_finance_term: int = 10  # years
    seller_balloon_year: int = 5  # balloon payment due
    seller_ltv_carry: float = 0.85  # seller willing to carry up to 85%
    master_lease_term: int = 3  # years
    option_price_premium: float = 0.05  # 5% above current value
    max_out_of_pocket: float = 50_000  # creative deal target


@dataclass
class ValueAddAssumptions:
    """Renovation and value-add parameters."""
    capex_per_unit: float = 15_000
    rent_bump_per_unit: float = 200  # monthly increase post-reno
    reno_timeline_months: int = 18
    units_renovated_per_month: int = 3
    expense_reduction_pct: float = 0.05  # 5% expense savings



# =============================================================================
# SECTION 2: CORE FINANCIAL FUNCTIONS
# =============================================================================

def monthly_payment(principal: float, annual_rate: float, years: int) -> float:
    """Calculate monthly mortgage payment (P&I)."""
    if annual_rate == 0:
        return principal / (years * 12)
    r = annual_rate / 12
    n = years * 12
    return principal * (r * (1 + r)**n) / ((1 + r)**n - 1)


def annual_debt_service(principal: float, annual_rate: float, amort_years: int) -> float:
    """Annual debt service (12 * monthly payment)."""
    return monthly_payment(principal, annual_rate, amort_years) * 12


def loan_balance_at_year(principal: float, annual_rate: float, amort_years: int, year: int) -> float:
    """Remaining loan balance at end of given year."""
    r = annual_rate / 12
    n = amort_years * 12
    payments_made = year * 12
    if annual_rate == 0:
        return principal - (principal / n) * payments_made
    balance = principal * ((1 + r)**n - (1 + r)**payments_made) / ((1 + r)**n - 1)
    return max(balance, 0)


def calculate_irr(cash_flows: list, max_iter: int = 1000, tol: float = 1e-6) -> float:
    """Calculate IRR using Newton's method with bounds protection."""
    # Initial guess
    rate = 0.10
    for _ in range(max_iter):
        try:
            npv = sum(cf / (1 + rate)**t for t, cf in enumerate(cash_flows))
            dnpv = sum(-t * cf / (1 + rate)**(t + 1) for t, cf in enumerate(cash_flows))
        except (OverflowError, ZeroDivisionError):
            return 0.0
        if abs(dnpv) < tol:
            break
        new_rate = rate - npv / dnpv
        # Clamp to reasonable range to prevent divergence
        new_rate = max(-0.99, min(new_rate, 10.0))
        if abs(new_rate - rate) < tol:
            return new_rate
        rate = new_rate
    return rate



# =============================================================================
# SECTION 3: BACKWARD ANALYSIS ENGINE
# =============================================================================

class BackwardAnalysisModel:
    """
    Main engine: starts from retirement goal, works backward to deal criteria.
    """

    def __init__(
        self,
        retirement: RetirementGoal = None,
        debt: DebtAssumptions = None,
        market: MarketAssumptions = None,
        investor: InvestorAssumptions = None,
        creative: CreativeFinanceAssumptions = None,
        value_add: ValueAddAssumptions = None,
    ):
        self.retirement = retirement or RetirementGoal()
        self.debt = debt or DebtAssumptions()
        self.market = market or MarketAssumptions()
        self.investor = investor or InvestorAssumptions()
        self.creative = creative or CreativeFinanceAssumptions()
        self.value_add = value_add or ValueAddAssumptions()
        self.results = {}

    # -----------------------------------------------------------------
    # STEP 1: Backward-solve from retirement income
    # -----------------------------------------------------------------
    def solve_retirement_target(self) -> dict:
        """From desired income, calculate required NOI and property size per deal."""
        r = self.retirement
        # Gross-up for taxes to get pre-tax cash flow needed
        pre_tax_income_needed = r.annual_passive_income / (1 - r.tax_rate)
        income_per_property = pre_tax_income_needed / r.num_properties

        # Cash-on-cash = annual cash flow / total equity invested
        # So: equity_per_deal = income_per_property / min_cash_on_cash
        equity_per_deal = income_per_property / r.min_cash_on_cash
        total_equity_needed = equity_per_deal * r.num_properties

        # NOI must cover debt service + cash flow to me
        # At target LTV: loan = purchase_price * LTV
        # purchase_price = NOI / cap_rate
        # ADS = f(loan, rate, amort)
        # Cash flow = NOI - ADS - reserves
        # We need: cash_flow >= income_per_property

        # Solve iteratively: find NOI where cash_flow = income_per_property
        # NOI - ADS(NOI/cap * LTV, rate, amort) = income_per_property
        cap = self.market.cap_rate_market
        ltv = self.debt.ltv_target
        rate = self.debt.interest_rate
        amort = self.debt.amortization_years

        # Analytical solve:
        # price = NOI / cap
        # loan = price * ltv = NOI * ltv / cap
        # ADS = loan * (r*(1+r)^n / ((1+r)^n - 1)) * 12  [monthly to annual]
        # Let K = annual constant per dollar of loan
        r_monthly = rate / 12
        n_months = amort * 12
        K = (r_monthly * (1 + r_monthly)**n_months / ((1 + r_monthly)**n_months - 1)) * 12

        # NOI - (NOI * ltv / cap) * K = income_per_property
        # NOI * (1 - ltv * K / cap) = income_per_property
        debt_burden_factor = ltv * K / cap
        if debt_burden_factor >= 1:
            # Deal cannot cash flow — LTV/rate too high for this cap rate
            noi_required = float('inf')
        else:
            noi_required = income_per_property / (1 - debt_burden_factor)

        purchase_price = noi_required / cap
        loan_amount = purchase_price * ltv
        ads = loan_amount * K
        cash_flow_year1 = noi_required - ads

        # Implied units needed
        monthly_rent = self.market.avg_market_rent_per_unit
        annual_gpi_per_unit = monthly_rent * 12
        egi_per_unit = annual_gpi_per_unit * (1 - self.market.vacancy_rate)
        noi_per_unit = egi_per_unit * (1 - self.market.expense_ratio)
        units_needed = math.ceil(noi_required / noi_per_unit)

        # Down payment
        down_payment = purchase_price * (1 - ltv)
        closing_costs = loan_amount * self.debt.origination_costs_pct
        total_cash_to_close = down_payment + closing_costs

        result = {
            "pre_tax_income_needed_total": pre_tax_income_needed,
            "income_per_property": income_per_property,
            "equity_per_deal": equity_per_deal,
            "total_equity_needed": total_equity_needed,
            "noi_required_per_deal": noi_required,
            "purchase_price_per_deal": purchase_price,
            "loan_amount": loan_amount,
            "annual_debt_service": ads,
            "cash_flow_year1": cash_flow_year1,
            "units_needed": units_needed,
            "down_payment": down_payment,
            "closing_costs": closing_costs,
            "total_cash_to_close": total_cash_to_close,
            "debt_burden_factor": debt_burden_factor,
            "price_per_unit": purchase_price / units_needed if units_needed > 0 else 0,
            "dscr_actual": noi_required / ads if ads > 0 else 0,
        }
        self.results["retirement"] = result
        return result


    # -----------------------------------------------------------------
    # STEP 2: Debt & LTV Constraint Validation
    # -----------------------------------------------------------------
    def validate_debt_structure(self) -> dict:
        """Check if the deal supports conventional lending parameters."""
        if "retirement" not in self.results:
            self.solve_retirement_target()

        ret = self.results["retirement"]
        noi = ret["noi_required_per_deal"]
        price = ret["purchase_price_per_deal"]

        # Max loan from DSCR constraint
        r_monthly = self.debt.interest_rate / 12
        n_months = self.debt.amortization_years * 12
        K = (r_monthly * (1 + r_monthly)**n_months / ((1 + r_monthly)**n_months - 1)) * 12
        max_loan_dscr = noi / (self.debt.dscr_required * K)

        # Max loan from LTV constraint
        max_loan_ltv = price * self.debt.ltv_max

        # Binding constraint is the lesser
        max_loan = min(max_loan_dscr, max_loan_ltv)
        binding_constraint = "DSCR" if max_loan_dscr < max_loan_ltv else "LTV"

        # Implied LTV at DSCR-constrained loan
        implied_ltv = max_loan_dscr / price if price > 0 else 0

        # Spread analysis
        debt_yield = noi / max_loan if max_loan > 0 else 0
        cost_of_debt = K  # annual constant (debt yield equivalent)
        cap_rate = self.market.cap_rate_market
        spread_bps = (cap_rate - self.debt.interest_rate) * 10000

        # Breakeven occupancy
        ads = max_loan * K
        total_expenses_fixed = noi * self.market.expense_ratio / (1 - self.market.expense_ratio)
        gpi = noi / ((1 - self.market.vacancy_rate) * (1 - self.market.expense_ratio))
        breakeven_occ = (ads + total_expenses_fixed) / gpi if gpi > 0 else 1.0

        # Stress test: rates +150bps at refinance
        stress_rate = self.debt.interest_rate + 0.015
        r_stress = stress_rate / 12
        K_stress = (r_stress * (1 + r_stress)**n_months / ((1 + r_stress)**n_months - 1)) * 12
        loan_at_refi = loan_balance_at_year(
            ret["loan_amount"], self.debt.interest_rate,
            self.debt.amortization_years, self.debt.loan_term_years
        )
        ads_stress = loan_at_refi * K_stress
        # Assume NOI has grown
        noi_at_refi = noi * (1 + self.market.annual_rent_growth) ** self.debt.loan_term_years
        dscr_stress = noi_at_refi / ads_stress if ads_stress > 0 else 0
        cash_flow_stress = noi_at_refi - ads_stress

        # Verdict
        conventional_viable = (
            implied_ltv <= self.debt.ltv_max and
            ret["dscr_actual"] >= self.debt.dscr_required and
            spread_bps >= 0
        )

        result = {
            "max_loan_dscr": max_loan_dscr,
            "max_loan_ltv": max_loan_ltv,
            "max_loan_binding": max_loan,
            "binding_constraint": binding_constraint,
            "implied_ltv_at_dscr": implied_ltv,
            "spread_cap_vs_debt_bps": spread_bps,
            "debt_yield": debt_yield,
            "breakeven_occupancy": breakeven_occ,
            "stress_test_dscr": dscr_stress,
            "stress_test_cash_flow": cash_flow_stress,
            "stress_rate_used": stress_rate,
            "conventional_viable": conventional_viable,
            "verdict": "CONVENTIONAL FINANCING VIABLE" if conventional_viable
                       else "CREATIVE STRUCTURE REQUIRED",
        }
        self.results["debt"] = result
        return result


    # -----------------------------------------------------------------
    # STEP 3: Investor Marketability (Syndication Feasibility)
    # -----------------------------------------------------------------
    def analyze_investor_marketability(self) -> dict:
        """Determine if the deal can attract passive investor capital."""
        if "retirement" not in self.results:
            self.solve_retirement_target()

        ret = self.results["retirement"]
        inv = self.investor
        va = self.value_add
        mkt = self.market

        price = ret["purchase_price_per_deal"]
        units = ret["units_needed"]
        noi_year1 = ret["noi_required_per_deal"]
        loan = ret["loan_amount"]

        # Total capital raise
        down_payment = ret["down_payment"]
        closing_costs = ret["closing_costs"]
        capex_budget = units * va.capex_per_unit
        operating_reserves = (ret["annual_debt_service"] / 12) * inv.reserve_months
        total_raise = down_payment + closing_costs + capex_budget + operating_reserves

        # Number of investors needed
        num_investors = math.ceil(total_raise / inv.min_investment_per_lp)

        # LP/GP split of equity
        gp_equity = self.retirement.cash_available  # GP co-invest
        lp_equity = total_raise - gp_equity
        lp_ownership = (1 - inv.gp_promote_after_pref)  # Before promote

        # Project annual cash flows to LPs (5-year hold)
        hold = inv.hold_period_years
        annual_cash_flows_total = []
        annual_cash_flows_lp = []
        noi_schedule = []

        for year in range(1, hold + 1):
            # Phased rent bumps from value-add
            months_elapsed = year * 12
            units_complete = min(units, int(va.units_renovated_per_month * min(months_elapsed, va.reno_timeline_months)))
            rent_bump_income = units_complete * va.rent_bump_per_unit * 12

            # NOI growth (organic + value-add)
            organic_noi = noi_year1 * (1 + mkt.annual_rent_growth) ** year
            total_noi = organic_noi + rent_bump_income * (1 - mkt.expense_ratio)
            noi_schedule.append(total_noi)

            # Cash flow after debt service
            ads = ret["annual_debt_service"]
            cf_total = total_noi - ads
            annual_cash_flows_total.append(cf_total)

            # LP share (pref + remaining split)
            pref_payment = lp_equity * inv.preferred_return
            excess = max(0, cf_total - pref_payment - (gp_equity * inv.preferred_return))
            lp_cash = pref_payment + excess * (1 - inv.gp_promote_after_pref)
            annual_cash_flows_lp.append(lp_cash)

        # Exit valuation
        stabilized_noi = noi_schedule[-1]
        exit_value = stabilized_noi / mkt.exit_cap_rate
        remaining_loan = loan_balance_at_year(
            loan, self.debt.interest_rate, self.debt.amortization_years, hold
        )
        net_sale_proceeds = exit_value * 0.97 - remaining_loan  # 3% disposition costs

        # LP exit proceeds
        lp_return_of_capital = lp_equity
        excess_proceeds = net_sale_proceeds - total_raise  # above original investment
        lp_exit = lp_return_of_capital + excess_proceeds * (1 - inv.gp_promote_after_pref)
        gp_exit = net_sale_proceeds - lp_exit

        # LP equity multiple
        total_lp_distributions = sum(annual_cash_flows_lp) + lp_exit
        lp_equity_multiple = total_lp_distributions / lp_equity if lp_equity > 0 else 0

        # LP IRR
        lp_cf_series = [-lp_equity] + annual_cash_flows_lp[:-1] + [annual_cash_flows_lp[-1] + lp_exit]
        try:
            lp_irr = calculate_irr(lp_cf_series)
        except:
            lp_irr = 0

        # GP returns
        gp_annual_cash = [cf - lp_cf for cf, lp_cf in zip(annual_cash_flows_total, annual_cash_flows_lp)]
        total_gp_cash = sum(gp_annual_cash) + gp_exit

        # Marketability scoring
        meets_pref = annual_cash_flows_lp[0] / lp_equity >= inv.preferred_return * 0.9
        meets_multiple = lp_equity_multiple >= inv.target_equity_multiple * 0.9
        meets_irr = lp_irr >= inv.target_irr * 0.9
        has_value_add_story = va.rent_bump_per_unit >= 100
        has_clear_exit = True  # Defined hold period with refi/sale

        marketability_score = sum([meets_pref, meets_multiple, meets_irr, has_value_add_story, has_clear_exit])
        marketability_grade = {5: "A", 4: "B+", 3: "B", 2: "C", 1: "D", 0: "F"}[marketability_score]

        result = {
            "total_capital_raise": total_raise,
            "down_payment": down_payment,
            "closing_costs": closing_costs,
            "capex_budget": capex_budget,
            "operating_reserves": operating_reserves,
            "num_investors_needed": num_investors,
            "lp_equity": lp_equity,
            "gp_equity": gp_equity,
            "annual_cash_flows_lp": annual_cash_flows_lp,
            "annual_cash_flows_total": annual_cash_flows_total,
            "noi_schedule": noi_schedule,
            "exit_value": exit_value,
            "net_sale_proceeds": net_sale_proceeds,
            "lp_exit_proceeds": lp_exit,
            "gp_exit_proceeds": gp_exit,
            "lp_equity_multiple": lp_equity_multiple,
            "lp_irr": lp_irr,
            "total_gp_earnings": total_gp_cash,
            "meets_pref": meets_pref,
            "meets_multiple": meets_multiple,
            "meets_irr": meets_irr,
            "marketability_score": f"{marketability_score}/5",
            "marketability_grade": marketability_grade,
            "can_raise_in_60_days": marketability_score >= 4,
            "raise_verdict": f"{'YES' if marketability_score >= 4 else 'DIFFICULT'} - "
                            f"Can fill ${total_raise:,.0f} raise "
                            f"({'easily' if marketability_score >= 4 else 'with effort'})",
        }
        self.results["investor"] = result
        return result


    # -----------------------------------------------------------------
    # STEP 4: Creative Financing Feasibility
    # -----------------------------------------------------------------
    def analyze_creative_financing(self) -> dict:
        """Evaluate seller finance, subject-to, and master lease options."""
        if "retirement" not in self.results:
            self.solve_retirement_target()

        ret = self.results["retirement"]
        cf = self.creative
        mkt = self.market

        price = ret["purchase_price_per_deal"]
        noi = ret["noi_required_per_deal"]
        units = ret["units_needed"]

        # --- SELLER FINANCING ---
        seller_loan = price * cf.seller_ltv_carry
        seller_down = price - seller_loan
        seller_ads = annual_debt_service(seller_loan, cf.seller_finance_rate, cf.seller_finance_term)
        seller_cf = noi - seller_ads
        seller_dscr = noi / seller_ads if seller_ads > 0 else 0
        seller_balloon = loan_balance_at_year(
            seller_loan, cf.seller_finance_rate, cf.seller_finance_term, cf.seller_balloon_year
        )

        # Seller's tax benefit of installment sale (simplified)
        # Spread capital gains over term vs lump sum
        assumed_seller_basis = price * 0.40  # Assume seller's cost basis is 40% of price
        total_gain = price - assumed_seller_basis
        annual_gain_recognized = total_gain / cf.seller_finance_term
        lump_sum_tax = total_gain * 0.20  # 20% LTCG
        installment_tax_per_year = annual_gain_recognized * 0.20
        seller_tax_savings = lump_sum_tax * 0.10  # Time value benefit (~10%)

        # Seller motivation indicators
        seller_motivation_factors = {
            "below_market_rents": mkt.avg_market_rent_per_unit < 1_000,
            "likely_tired_landlord": True,  # User should override based on research
            "deferred_maintenance": True,   # Common in value-add targets
            "long_hold_period": True,       # Assume 10+ years
            "fully_depreciated": True,      # If long hold, likely
            "estate_or_partnership": False,  # User should verify
        }
        motivation_score = sum(seller_motivation_factors.values())

        seller_finance_viable = (
            seller_cf > 0 and
            seller_dscr >= 1.10 and
            seller_down <= cf.max_out_of_pocket * 3  # Some flexibility
        )

        # --- SUBJECT-TO / WRAP ---
        # Assume existing debt is ~50% of current value at below-market rate
        existing_debt = price * 0.50
        existing_rate = 0.045  # Older loan, lower rate
        existing_ads = annual_debt_service(existing_debt, existing_rate, 25)
        gap_financing_needed = price - existing_debt - cf.max_out_of_pocket
        wrap_cf = noi - existing_ads
        sub_to_viable = wrap_cf > 0 and gap_financing_needed < price * 0.20

        # --- MASTER LEASE WITH OPTION ---
        # Lease payment must cover seller's debt service + small return
        seller_existing_debt_service = existing_ads
        master_lease_payment = seller_existing_debt_service * 1.10  # 10% above their debt
        ml_cash_flow = noi - master_lease_payment
        option_strike = price * (1 + cf.option_price_premium)

        # Can I reposition and refi during lease?
        stabilized_noi_post_reno = noi + (units * self.value_add.rent_bump_per_unit * 12 *
                                          (1 - mkt.expense_ratio))
        refi_value = stabilized_noi_post_reno / mkt.cap_rate_market
        refi_loan_75 = refi_value * 0.75
        can_cash_out_refi = refi_loan_75 >= option_strike

        master_lease_viable = ml_cash_flow > 0 and can_cash_out_refi

        # Overall creative verdict
        best_creative_structure = "NONE"
        min_out_of_pocket = float('inf')

        if seller_finance_viable:
            best_creative_structure = "SELLER FINANCING"
            min_out_of_pocket = seller_down
        if sub_to_viable and cf.max_out_of_pocket < min_out_of_pocket:
            best_creative_structure = "SUBJECT-TO"
            min_out_of_pocket = cf.max_out_of_pocket
        if master_lease_viable and 0 < min_out_of_pocket:
            # Master lease typically lowest entry cost
            ml_entry = master_lease_payment * 2  # First + last month + option fee
            if ml_entry < min_out_of_pocket:
                best_creative_structure = "MASTER LEASE W/ OPTION"
                min_out_of_pocket = ml_entry

        result = {
            "seller_finance": {
                "loan_amount": seller_loan,
                "down_payment": seller_down,
                "annual_debt_service": seller_ads,
                "cash_flow": seller_cf,
                "dscr": seller_dscr,
                "balloon_at_year": cf.seller_balloon_year,
                "balloon_amount": seller_balloon,
                "seller_tax_benefit": seller_tax_savings,
                "viable": seller_finance_viable,
            },
            "subject_to": {
                "existing_debt_assumed": existing_debt,
                "existing_rate": existing_rate,
                "existing_ads": existing_ads,
                "gap_financing": gap_financing_needed,
                "cash_flow": wrap_cf,
                "viable": sub_to_viable,
                "due_on_sale_risk": "MODERATE",
            },
            "master_lease": {
                "monthly_lease_payment": master_lease_payment / 12,
                "annual_lease_payment": master_lease_payment,
                "cash_flow_during_lease": ml_cash_flow,
                "option_strike_price": option_strike,
                "refi_value_post_reno": refi_value,
                "can_cash_out_refi": can_cash_out_refi,
                "viable": master_lease_viable,
            },
            "seller_motivation_score": f"{motivation_score}/6",
            "best_structure": best_creative_structure,
            "min_out_of_pocket": min_out_of_pocket,
            "creative_verdict": f"Control asset with ${min_out_of_pocket:,.0f} via {best_creative_structure}"
                                if best_creative_structure != "NONE"
                                else "NO VIABLE CREATIVE STRUCTURE - conventional required",
        }
        self.results["creative"] = result
        return result


    # -----------------------------------------------------------------
    # STEP 5: Deal Criteria Box (Final Output)
    # -----------------------------------------------------------------
    def generate_deal_criteria(self) -> dict:
        """Produce min/target/max acquisition criteria from backward analysis."""
        if "retirement" not in self.results:
            self.solve_retirement_target()
        if "investor" not in self.results:
            self.analyze_investor_marketability()

        ret = self.results["retirement"]
        inv = self.results.get("investor", {})
        va = self.value_add
        mkt = self.market

        price = ret["purchase_price_per_deal"]
        units = ret["units_needed"]
        noi = ret["noi_required_per_deal"]

        criteria = {
            "unit_count": {
                "minimum": max(20, int(units * 0.7)),
                "target": units,
                "maximum": int(units * 1.5),
            },
            "purchase_price": {
                "minimum": price * 0.75,
                "target": price,
                "maximum": price * 1.15,
            },
            "going_in_cap_rate": {
                "minimum": mkt.cap_rate_market - 0.005,
                "target": mkt.cap_rate_market,
                "maximum": mkt.cap_rate_market + 0.02,
            },
            "price_per_unit": {
                "minimum": price * 0.75 / (units * 1.5),
                "target": ret["price_per_unit"],
                "maximum": price * 1.15 / max(1, int(units * 0.7)),
            },
            "price_per_sf": {
                "minimum": (price * 0.75) / (units * 1.5 * mkt.avg_unit_sf),
                "target": price / (units * mkt.avg_unit_sf),
                "maximum": (price * 1.15) / (int(units * 0.7) * mkt.avg_unit_sf),
            },
            "current_occupancy": {
                "minimum": 0.80,
                "target": 0.90,
                "maximum": None,  # Higher is better
            },
            "in_place_noi": {
                "minimum": noi * 0.70,  # Value-add can be below stabilized
                "target": noi,
                "maximum": None,
            },
            "stabilized_noi": {
                "minimum": noi,
                "target": noi * 1.20,
                "maximum": None,
            },
            "rent_upside_per_unit_monthly": {
                "minimum": 100,
                "target": va.rent_bump_per_unit,
                "maximum": None,
            },
            "total_capex_budget": {
                "minimum": units * va.capex_per_unit * 0.5,
                "target": units * va.capex_per_unit,
                "maximum": units * va.capex_per_unit * 1.5,
            },
            "capex_per_unit": {
                "minimum": va.capex_per_unit * 0.5,
                "target": va.capex_per_unit,
                "maximum": va.capex_per_unit * 1.5,
            },
            "year1_cash_on_cash": {
                "minimum": self.retirement.min_cash_on_cash * 0.8,
                "target": self.retirement.min_cash_on_cash,
                "maximum": None,
            },
            "five_year_irr_levered": {
                "minimum": 0.14,
                "target": 0.18,
                "maximum": None,
            },
            "exit_cap_rate": {
                "minimum": mkt.exit_cap_rate - 0.005,
                "target": mkt.exit_cap_rate,
                "maximum": mkt.exit_cap_rate + 0.015,
            },
            "max_out_of_pocket_creative": {
                "minimum": 0,
                "target": self.creative.max_out_of_pocket,
                "maximum": self.creative.max_out_of_pocket * 3,
            },
            "capital_raise_syndication": {
                "minimum": inv.get("total_capital_raise", 0) * 0.8,
                "target": inv.get("total_capital_raise", 0),
                "maximum": inv.get("total_capital_raise", 0) * 1.3,
            },
        }
        self.results["criteria"] = criteria
        return criteria


    # -----------------------------------------------------------------
    # STEP 6: Sensitivity & Scenario Analysis
    # -----------------------------------------------------------------
    def run_scenarios(self) -> dict:
        """Bull, Base, Bear, and Catastrophe scenario modeling."""
        if "retirement" not in self.results:
            self.solve_retirement_target()

        ret = self.results["retirement"]
        mkt = self.market
        va = self.value_add
        inv = self.investor

        price = ret["purchase_price_per_deal"]
        units = ret["units_needed"]
        noi_year1 = ret["noi_required_per_deal"]
        loan = ret["loan_amount"]
        ads = ret["annual_debt_service"]
        hold = inv.hold_period_years

        scenarios = {}

        scenario_params = {
            "bull": {
                "rent_growth": mkt.annual_rent_growth + 0.01,
                "rent_bump_achieved": 1.0,
                "exit_cap": mkt.exit_cap_rate - 0.010,
                "vacancy": mkt.vacancy_rate - 0.02,
                "refi_rate_delta": -0.005,
                "label": "Full value-add, compressed exit cap, low vacancy",
            },
            "base": {
                "rent_growth": mkt.annual_rent_growth,
                "rent_bump_achieved": 0.80,
                "exit_cap": mkt.exit_cap_rate,
                "vacancy": mkt.vacancy_rate,
                "refi_rate_delta": 0,
                "label": "80% of rent bumps, market exit, normal vacancy",
            },
            "bear": {
                "rent_growth": 0.005,
                "rent_bump_achieved": 0.50,
                "exit_cap": mkt.exit_cap_rate + 0.015,
                "vacancy": mkt.vacancy_rate + 0.03,
                "refi_rate_delta": 0.01,
                "label": "Flat rents, cap expansion, elevated vacancy",
            },
            "catastrophe": {
                "rent_growth": -0.01,
                "rent_bump_achieved": 0.30,
                "exit_cap": mkt.exit_cap_rate + 0.025,
                "vacancy": mkt.vacancy_rate + 0.07,
                "refi_rate_delta": 0.02,
                "label": "Rent decline, rate spike, high vacancy",
            },
        }

        for name, params in scenario_params.items():
            # Project NOI over hold period
            noi_final = noi_year1
            for yr in range(1, hold + 1):
                organic = noi_final * (1 + params["rent_growth"])
                bump = (units * va.rent_bump_per_unit * params["rent_bump_achieved"]
                        * 12 * (1 - mkt.expense_ratio) / hold)  # Phased in
                noi_final = organic + bump

            # Adjust for vacancy change
            vacancy_impact = (params["vacancy"] - mkt.vacancy_rate) * noi_final
            noi_final_adj = noi_final + vacancy_impact  # negative if higher vacancy

            # Exit
            exit_value = noi_final_adj / params["exit_cap"]
            remaining_loan = loan_balance_at_year(
                loan, self.debt.interest_rate, self.debt.amortization_years, hold
            )
            net_proceeds = exit_value * 0.97 - remaining_loan
            total_equity_in = ret["total_cash_to_close"] + units * va.capex_per_unit

            # My personal annual cash flow (average over hold)
            avg_annual_cf = (noi_year1 + noi_final_adj) / 2 - ads
            equity_at_exit = net_proceeds
            equity_multiple = (avg_annual_cf * hold + equity_at_exit) / total_equity_in if total_equity_in > 0 else 0

            # Can I still retire on time?
            meets_retirement = avg_annual_cf * self.retirement.num_properties >= (
                self.retirement.annual_passive_income / (1 - self.retirement.tax_rate)
            )

            # Investor returns in this scenario
            lp_equity = total_equity_in - self.retirement.cash_available
            lp_cf_series = [-lp_equity]
            for yr in range(1, hold + 1):
                yr_noi = noi_year1 + (noi_final_adj - noi_year1) * yr / hold
                yr_cf = yr_noi - ads
                lp_share = yr_cf * (1 - inv.gp_promote_after_pref)
                lp_cf_series.append(lp_share)
            lp_cf_series[-1] += net_proceeds * (1 - inv.gp_promote_after_pref)
            try:
                scenario_irr = calculate_irr(lp_cf_series)
            except:
                scenario_irr = 0

            scenarios[name] = {
                "label": params["label"],
                "noi_at_exit": noi_final_adj,
                "exit_value": exit_value,
                "net_proceeds": net_proceeds,
                "avg_annual_cash_flow": avg_annual_cf,
                "equity_at_exit": equity_at_exit,
                "equity_multiple": equity_multiple,
                "investor_irr": scenario_irr,
                "meets_retirement_goal": meets_retirement,
                "survives": avg_annual_cf > 0 and net_proceeds > 0,
            }

        self.results["scenarios"] = scenarios
        return scenarios


    # -----------------------------------------------------------------
    # STEP 7: GO / NO-GO Decision Framework
    # -----------------------------------------------------------------
    def decision_framework(self) -> dict:
        """Produce final GO / NO-GO / NEGOTIATE recommendation."""
        # Run all analyses if not already done
        if "retirement" not in self.results:
            self.solve_retirement_target()
        if "debt" not in self.results:
            self.validate_debt_structure()
        if "investor" not in self.results:
            self.analyze_investor_marketability()
        if "creative" not in self.results:
            self.analyze_creative_financing()
        if "scenarios" not in self.results:
            self.run_scenarios()

        debt = self.results["debt"]
        inv = self.results["investor"]
        creative = self.results["creative"]
        scenarios = self.results["scenarios"]
        ret = self.results["retirement"]

        # Scoring
        conventional_works = debt["conventional_viable"]
        investor_attractive = inv["can_raise_in_60_days"]
        creative_works = creative["best_structure"] != "NONE"
        bear_survives = scenarios["bear"]["survives"]
        catastrophe_survives = scenarios["catastrophe"]["survives"]
        meets_retirement = scenarios["base"]["meets_retirement_goal"]

        # Decision logic
        if conventional_works and investor_attractive and bear_survives and meets_retirement:
            decision = "GO (CONVENTIONAL)"
            reasoning = (
                f"Deal pencils with conventional debt (DSCR {ret['dscr_actual']:.2f}x), "
                f"investor returns are marketable (Grade {inv['marketability_grade']}), "
                f"survives bear case, and meets retirement cash flow target."
            )
            action = (
                f"Proceed with LOI at ${ret['purchase_price_per_deal']:,.0f}. "
                f"Raise ${inv['total_capital_raise']:,.0f} from {inv['num_investors_needed']} investors."
            )
        elif creative_works and bear_survives and meets_retirement:
            decision = "GO (CREATIVE)"
            reasoning = (
                f"Deal requires creative structure ({creative['best_structure']}) "
                f"but math works. Entry cost: ${creative['min_out_of_pocket']:,.0f}. "
                f"Bear case survives."
            )
            action = (
                f"Approach seller with {creative['best_structure'].lower()} proposal. "
                f"Prepare creative finance pitch deck."
            )
        elif not bear_survives and scenarios["base"]["survives"]:
            decision = "NEGOTIATE"
            reasoning = (
                f"Deal works at base case but too thin for bear scenario. "
                f"Need price reduction or seller concession to create margin of safety."
            )
            # Calculate required price discount for bear case to work
            target_discount = 0.10  # Start with 10%
            action = (
                f"Counter at ${ret['purchase_price_per_deal'] * (1 - target_discount):,.0f} "
                f"({target_discount*100:.0f}% below ask) OR request seller credit/carry."
            )
        else:
            decision = "NO-GO"
            reasoning = (
                f"Spread too thin: cap rate vs debt spread = {debt['spread_cap_vs_debt_bps']:.0f} bps. "
                f"Returns don't justify risk. "
                f"{'Investor returns below threshold. ' if not investor_attractive else ''}"
                f"{'Does not survive bear case. ' if not bear_survives else ''}"
            )
            action = "Pass on this deal. Refine search criteria and move to next opportunity."

        result = {
            "decision": decision,
            "reasoning": reasoning,
            "recommended_action": action,
            "summary_scores": {
                "conventional_financing": "PASS" if conventional_works else "FAIL",
                "investor_marketability": inv["marketability_grade"],
                "creative_viability": "PASS" if creative_works else "FAIL",
                "bear_case_survival": "PASS" if bear_survives else "FAIL",
                "catastrophe_survival": "PASS" if catastrophe_survives else "FAIL",
                "retirement_goal": "PASS" if meets_retirement else "FAIL",
            },
        }
        self.results["decision"] = result
        return result

    # -----------------------------------------------------------------
    # FULL RUN: Execute all analyses
    # -----------------------------------------------------------------
    def run_full_analysis(self) -> dict:
        """Execute complete backward analysis pipeline."""
        self.solve_retirement_target()
        self.validate_debt_structure()
        self.analyze_investor_marketability()
        self.analyze_creative_financing()
        self.generate_deal_criteria()
        self.run_scenarios()
        self.decision_framework()
        return self.results



# =============================================================================
# SECTION 4: REPORT PRINTER
# =============================================================================

def print_report(model: BackwardAnalysisModel):
    """Print a formatted analysis report."""
    r = model.results

    print("=" * 80)
    print("   MULTIFAMILY BACKWARD ANALYSIS — RETIREMENT DEAL CRITERIA")
    print("=" * 80)

    # --- Retirement Target ---
    ret = r["retirement"]
    print("\n┌─────────────────────────────────────────────────────────────────────┐")
    print("│  SECTION 1: RETIREMENT INCOME — BACKWARD SOLUTION                   │")
    print("└─────────────────────────────────────────────────────────────────────┘")
    print(f"  Target passive income (after tax):  ${model.retirement.annual_passive_income:>12,.0f}/yr")
    print(f"  Pre-tax income needed (total):      ${ret['pre_tax_income_needed_total']:>12,.0f}/yr")
    print(f"  Income needed per property:         ${ret['income_per_property']:>12,.0f}/yr")
    print(f"  Number of properties:               {model.retirement.num_properties:>12}")
    print(f"  Timeline:                           {model.retirement.timeline_years:>12} years")
    print(f"  ─────────────────────────────────────────────────────────────────")
    print(f"  Required NOI per deal:              ${ret['noi_required_per_deal']:>12,.0f}")
    print(f"  Purchase price per deal:            ${ret['purchase_price_per_deal']:>12,.0f}")
    print(f"  Units needed per deal:              {ret['units_needed']:>12}")
    print(f"  Price per unit:                     ${ret['price_per_unit']:>12,.0f}")
    print(f"  Loan amount (@ {model.debt.ltv_target*100:.0f}% LTV):         ${ret['loan_amount']:>12,.0f}")
    print(f"  Annual debt service:                ${ret['annual_debt_service']:>12,.0f}")
    print(f"  Year 1 cash flow:                   ${ret['cash_flow_year1']:>12,.0f}")
    print(f"  DSCR:                               {ret['dscr_actual']:>12.2f}x")
    print(f"  Down payment:                       ${ret['down_payment']:>12,.0f}")
    print(f"  Closing costs:                      ${ret['closing_costs']:>12,.0f}")
    print(f"  Total cash to close:                ${ret['total_cash_to_close']:>12,.0f}")
    print(f"  Total equity needed (all deals):    ${ret['total_equity_needed']:>12,.0f}")

    # --- Debt Validation ---
    debt = r["debt"]
    print("\n┌─────────────────────────────────────────────────────────────────────┐")
    print("│  SECTION 2: DEBT & LTV VALIDATION                                   │")
    print("└─────────────────────────────────────────────────────────────────────┘")
    print(f"  Max loan (DSCR constrained):        ${debt['max_loan_dscr']:>12,.0f}")
    print(f"  Max loan (LTV constrained):         ${debt['max_loan_ltv']:>12,.0f}")
    print(f"  Binding constraint:                 {debt['binding_constraint']:>12}")
    print(f"  Implied LTV at DSCR limit:          {debt['implied_ltv_at_dscr']*100:>11.1f}%")
    print(f"  Cap rate vs debt cost spread:       {debt['spread_cap_vs_debt_bps']:>10.0f} bps")
    print(f"  Debt yield:                         {debt['debt_yield']*100:>11.1f}%")
    print(f"  Breakeven occupancy:                {debt['breakeven_occupancy']*100:>11.1f}%")
    print(f"  ─── Stress Test (rates +150bps) ───")
    print(f"  Stress DSCR at refi:                {debt['stress_test_dscr']:>12.2f}x")
    print(f"  Stress cash flow at refi:           ${debt['stress_test_cash_flow']:>12,.0f}")
    print(f"  ─────────────────────────────────────────────────────────────────")
    print(f"  ▶ VERDICT: {debt['verdict']}")


    # --- Investor Marketability ---
    inv = r["investor"]
    print("\n┌─────────────────────────────────────────────────────────────────────┐")
    print("│  SECTION 3: INVESTOR MARKETABILITY (SYNDICATION)                     │")
    print("└─────────────────────────────────────────────────────────────────────┘")
    print(f"  Total capital raise:                ${inv['total_capital_raise']:>12,.0f}")
    print(f"    Down payment:                     ${inv['down_payment']:>12,.0f}")
    print(f"    Closing costs:                    ${inv['closing_costs']:>12,.0f}")
    print(f"    Capex budget:                     ${inv['capex_budget']:>12,.0f}")
    print(f"    Operating reserves:               ${inv['operating_reserves']:>12,.0f}")
    print(f"  LP equity:                          ${inv['lp_equity']:>12,.0f}")
    print(f"  GP co-invest:                       ${inv['gp_equity']:>12,.0f}")
    print(f"  Investors needed (@ ${model.investor.min_investment_per_lp:,.0f} min): {inv['num_investors_needed']:>7}")
    print(f"  ─── LP Returns ───")
    print(f"  LP equity multiple:                 {inv['lp_equity_multiple']:>12.2f}x")
    print(f"  LP IRR:                             {inv['lp_irr']*100:>11.1f}%")
    print(f"  Meets pref return:                  {'YES' if inv['meets_pref'] else 'NO':>12}")
    print(f"  Meets equity multiple:              {'YES' if inv['meets_multiple'] else 'NO':>12}")
    print(f"  Meets IRR target:                   {'YES' if inv['meets_irr'] else 'NO':>12}")
    print(f"  ─── Cash Flow to LPs (Annual) ───")
    for i, cf in enumerate(inv['annual_cash_flows_lp'], 1):
        print(f"    Year {i}:                           ${cf:>12,.0f}")
    print(f"  Exit proceeds to LPs:               ${inv['lp_exit_proceeds']:>12,.0f}")
    print(f"  ─────────────────────────────────────────────────────────────────")
    print(f"  Marketability Grade:                {inv['marketability_grade']:>12}")
    print(f"  Score:                              {inv['marketability_score']:>12}")
    print(f"  ▶ VERDICT: {inv['raise_verdict']}")

    # --- Creative Financing ---
    cre = r["creative"]
    print("\n┌─────────────────────────────────────────────────────────────────────┐")
    print("│  SECTION 4: CREATIVE FINANCING OPTIONS                               │")
    print("└─────────────────────────────────────────────────────────────────────┘")
    sf = cre["seller_finance"]
    print(f"  ─── Seller Financing ───")
    print(f"  Seller carry amount:                ${sf['loan_amount']:>12,.0f}")
    print(f"  Down payment to seller:             ${sf['down_payment']:>12,.0f}")
    print(f"  Annual debt service:                ${sf['annual_debt_service']:>12,.0f}")
    print(f"  Cash flow:                          ${sf['cash_flow']:>12,.0f}")
    print(f"  DSCR:                               {sf['dscr']:>12.2f}x")
    print(f"  Balloon at year {sf['balloon_at_year']}:                 ${sf['balloon_amount']:>12,.0f}")
    print(f"  Viable:                             {'YES' if sf['viable'] else 'NO':>12}")
    st = cre["subject_to"]
    print(f"  ─── Subject-To ───")
    print(f"  Existing debt assumed:              ${st['existing_debt_assumed']:>12,.0f}")
    print(f"  Gap financing needed:               ${st['gap_financing']:>12,.0f}")
    print(f"  Cash flow:                          ${st['cash_flow']:>12,.0f}")
    print(f"  Due-on-sale risk:                   {st['due_on_sale_risk']:>12}")
    print(f"  Viable:                             {'YES' if st['viable'] else 'NO':>12}")
    ml = cre["master_lease"]
    print(f"  ─── Master Lease w/ Option ───")
    print(f"  Monthly lease payment:              ${ml['monthly_lease_payment']:>12,.0f}")
    print(f"  Cash flow during lease:             ${ml['cash_flow_during_lease']:>12,.0f}")
    print(f"  Option strike price:                ${ml['option_strike_price']:>12,.0f}")
    print(f"  Refi value post-reno:               ${ml['refi_value_post_reno']:>12,.0f}")
    print(f"  Can cash-out refi to exercise:      {'YES' if ml['can_cash_out_refi'] else 'NO':>12}")
    print(f"  Viable:                             {'YES' if ml['viable'] else 'NO':>12}")
    print(f"  ─────────────────────────────────────────────────────────────────")
    print(f"  Seller motivation score:            {cre['seller_motivation_score']:>12}")
    print(f"  ▶ BEST STRUCTURE: {cre['best_structure']}")
    print(f"  ▶ VERDICT: {cre['creative_verdict']}")


    # --- Deal Criteria Box ---
    criteria = r["criteria"]
    print("\n┌─────────────────────────────────────────────────────────────────────┐")
    print("│  SECTION 5: ACQUISITION CRITERIA BOX                                 │")
    print("└─────────────────────────────────────────────────────────────────────┘")
    print(f"  {'Parameter':<30} {'Minimum':>12} {'Target':>12} {'Maximum':>12}")
    print(f"  {'─'*30} {'─'*12} {'─'*12} {'─'*12}")

    def fmt(val, is_pct=False, is_dollar=True):
        if val is None:
            return "     —"
        if is_pct:
            return f"{val*100:>10.1f}%"
        if is_dollar:
            return f"${val:>11,.0f}"
        return f"{val:>12,.0f}"

    rows = [
        ("Unit count", criteria["unit_count"], False, False),
        ("Purchase price", criteria["purchase_price"], False, True),
        ("Going-in cap rate", criteria["going_in_cap_rate"], True, False),
        ("Price per unit", criteria["price_per_unit"], False, True),
        ("Price per SF", criteria["price_per_sf"], False, True),
        ("Current occupancy", criteria["current_occupancy"], True, False),
        ("In-place NOI", criteria["in_place_noi"], False, True),
        ("Stabilized NOI", criteria["stabilized_noi"], False, True),
        ("Rent upside/unit (mo)", criteria["rent_upside_per_unit_monthly"], False, True),
        ("Total capex budget", criteria["total_capex_budget"], False, True),
        ("Capex per unit", criteria["capex_per_unit"], False, True),
        ("Year 1 CoC", criteria["year1_cash_on_cash"], True, False),
        ("5-Year IRR (levered)", criteria["five_year_irr_levered"], True, False),
        ("Exit cap rate", criteria["exit_cap_rate"], True, False),
        ("Max OOP (creative)", criteria["max_out_of_pocket_creative"], False, True),
        ("Capital raise (syndication)", criteria["capital_raise_syndication"], False, True),
    ]

    for name, vals, is_pct, is_dollar in rows:
        mn = fmt(vals["minimum"], is_pct, is_dollar)
        tg = fmt(vals["target"], is_pct, is_dollar)
        mx = fmt(vals["maximum"], is_pct, is_dollar)
        print(f"  {name:<30} {mn:>12} {tg:>12} {mx:>12}")

    # --- Scenarios ---
    scenarios = r["scenarios"]
    print("\n┌─────────────────────────────────────────────────────────────────────┐")
    print("│  SECTION 6: SCENARIO ANALYSIS                                        │")
    print("└─────────────────────────────────────────────────────────────────────┘")
    print(f"  {'Scenario':<14} {'NOI@Exit':>12} {'Exit Value':>12} {'Avg CF/yr':>12} "
          f"{'Eq Multiple':>12} {'Inv IRR':>8} {'Retire?':>8} {'Survive?':>8}")
    print(f"  {'─'*14} {'─'*12} {'─'*12} {'─'*12} {'─'*12} {'─'*8} {'─'*8} {'─'*8}")

    for name, s in scenarios.items():
        irr_display = s['investor_irr'] * 100
        irr_str = f"{irr_display:>6.1f}%" if -100 < irr_display < 1000 else "  N/A "
        print(f"  {name.upper():<14} "
              f"${s['noi_at_exit']:>10,.0f} "
              f"${s['exit_value']:>10,.0f} "
              f"${s['avg_annual_cash_flow']:>10,.0f} "
              f"{s['equity_multiple']:>11.2f}x "
              f"{irr_str} "
              f"{'YES' if s['meets_retirement_goal'] else 'NO':>8} "
              f"{'YES' if s['survives'] else 'NO':>8}")

    # --- Final Decision ---
    dec = r["decision"]
    print("\n┌─────────────────────────────────────────────────────────────────────┐")
    print("│  SECTION 7: DECISION FRAMEWORK                                       │")
    print("└─────────────────────────────────────────────────────────────────────┘")
    print(f"\n  ╔═══════════════════════════════════════════════════════════════════╗")
    print(f"  ║  DECISION: {dec['decision']:<55}║")
    print(f"  ╚═══════════════════════════════════════════════════════════════════╝")
    print(f"\n  Reasoning: {dec['reasoning']}")
    print(f"\n  Action: {dec['recommended_action']}")
    print(f"\n  Summary Scores:")
    for metric, score in dec["summary_scores"].items():
        icon = "✓" if score == "PASS" or score in ["A", "B+", "B"] else "✗"
        print(f"    {icon} {metric.replace('_', ' ').title():<30} {score}")

    print("\n" + "=" * 80)
    print("  END OF ANALYSIS")
    print("=" * 80)



# =============================================================================
# SECTION 5: MAIN — DEMO RUN WITH SAMPLE INPUTS
# =============================================================================

if __name__ == "__main__":
    print("\n" + "=" * 80)
    print("  RUNNING BACKWARD ANALYSIS WITH SAMPLE INPUTS")
    print("=" * 80)
    print("""
  Sample Investor Profile:
    - Retirement income goal: $200,000/year net passive
    - Timeline: 5 years
    - Properties at retirement: 3
    - Cash available for first deal: $150,000
    - Strategy: Value-add multifamily (syndication or creative)
    - Risk tolerance: Moderate (no negative CF in Year 1)
    - Target market: Secondary MSA, avg rent $1,200/unit
    """)

    # Initialize with default assumptions (modify these for your market)
    model = BackwardAnalysisModel(
        retirement=RetirementGoal(
            annual_passive_income=200_000,
            timeline_years=5,
            min_cash_on_cash=0.10,
            num_properties=3,
            tax_rate=0.30,
            cash_available=150_000,
        ),
        debt=DebtAssumptions(
            ltv_target=0.75,
            dscr_required=1.25,
            interest_rate=0.065,
            amortization_years=30,
            loan_term_years=7,
            origination_costs_pct=0.025,
        ),
        market=MarketAssumptions(
            avg_market_rent_per_unit=1_200,
            avg_unit_sf=850,
            vacancy_rate=0.07,
            expense_ratio=0.45,
            annual_rent_growth=0.03,
            cap_rate_market=0.065,
            exit_cap_rate=0.070,
        ),
        investor=InvestorAssumptions(
            preferred_return=0.08,
            target_equity_multiple=2.0,
            target_irr=0.17,
            hold_period_years=5,
            gp_promote_after_pref=0.30,
            min_investment_per_lp=50_000,
        ),
        creative=CreativeFinanceAssumptions(
            seller_finance_rate=0.05,
            seller_finance_term=10,
            seller_balloon_year=5,
            seller_ltv_carry=0.85,
            max_out_of_pocket=50_000,
        ),
        value_add=ValueAddAssumptions(
            capex_per_unit=15_000,
            rent_bump_per_unit=200,
            reno_timeline_months=18,
            units_renovated_per_month=3,
        ),
    )

    # Run full analysis
    model.run_full_analysis()

    # Print formatted report
    print_report(model)

    print("\n\n  💡 TO CUSTOMIZE: Edit the dataclass inputs above with your actual")
    print("     market data, personal goals, and deal-specific numbers.")
    print("     Then re-run to get your personalized acquisition criteria.\n")
